Record value expressions RFC
cortezaproject/corteza-docs pull request #100
Opened 2020-11-12 06:51 UTC by darh

2020-11-12 09:45 UTC, tjerman requested changes
There are some grammar issues; I can go over it once you're done with it.

2020-11-12 09:45 UTC, tjerman commented on src/modules/ROOT/pages/rfc/record-value-expr/index.adoc
> +When expression on the field input value on this field is ignored and expression is evaluated instead.
I can't make this out; can you please rewrite this one

2020-11-12 09:45 UTC, tjerman commented on src/modules/ROOT/pages/rfc/record-value-expr/index.adoc
> + - formula
Use `*` for UL

2020-11-12 09:45 UTC, tjerman commented on src/modules/ROOT/pages/rfc/record-value-expr/index.adoc
> +Module field Expressions enables support for arbitraty expressions on moduel fields and unlock:
~moduel~ -- module

2020-11-12 09:45 UTC, tjerman commented on src/modules/ROOT/pages/rfc/record-value-expr/index.adoc
> + - If expression on single-value fields does not return single value, system raises error
Use `*` and end each one with a `.`

2020-11-12 09:45 UTC, tjerman commented on src/modules/ROOT/pages/rfc/record-value-expr/index.adoc
> +| String or array of strings with new value.
I would prefer to see this in this form:

```
* `old`: the original record object.
* `new`: the new record object.
* `<field-name>`: String or array of strings with new value.
```

2020-11-12 09:45 UTC, tjerman commented on src/modules/ROOT/pages/rfc/record-value-expr/index.adoc
> +If field name collides with any of reserved variables (old, new, field, module) it can be accessed via `old.values.<field-name>`
I'd use a `[NOTE]` here.

Missing `.`

2020-11-12 09:45 UTC, tjerman commented on src/modules/ROOT/pages/rfc/record-value-expr/index.adoc
> +Only one variable is exposed to the sanitizer
`.`

2020-11-12 09:45 UTC, tjerman commented on src/modules/ROOT/pages/rfc/record-value-expr/index.adoc
> +|===
Same as above (regarding list vs table)

2020-11-12 09:45 UTC, tjerman commented on src/modules/ROOT/pages/rfc/record-value-expr/index.adoc
> +|===
Same as above; applies to all that follow

2020-11-12 09:45 UTC, tjerman commented on src/modules/ROOT/pages/rfc/record-value-expr/index.adoc
> +|===
This I would leave as it is (in a table); wrap the signature in a snippet

2020-12-01 18:07 UTC, darh commented
Updated. 

Kindly asking @Fajfa to update the table at the end with the data he's working on for the frontend.

2020-12-02 16:07 UTC, Fajfa commented
Table updated so it reflects the frontend help page tables

2020-12-08 08:14 UTC, tjerman commented
Merged into https://github.com/cortezaproject/corteza-docs/commit/fa22e50de7dcc4b9f0d5dbdef66d1cea76171d54

2020-12-08 08:14 UTC, closed without merging