Document page duplication
cortezaproject/corteza-docs pull request #369
Opened 2023-02-21 17:43 UTC by katrinDY

2023-02-21 17:45 UTC, katrinDY commented
How it looks

<img width="1495" alt="Screenshot 2023-02-21 at 19 44 24" src="https://user-images.githubusercontent.com/85161724/220420609-d776188c-4a76-439d-b051-c6221e7f8557.png">

2023-02-22 09:57 UTC, tjerman reviewed
Consider moving this section lower down and make it a subtitle. It's sort of an addition to the _main flow_.
Consider adding some screenshots.

Run it through Grammarly; fix if needed

2023-02-22 09:57 UTC, tjerman commented on src/modules/integrator-guide/pages/compose-configuration/index.adoc
> +To copy the contents of another list page, navigate to the page itself and click on the 'Save as copy' button.
`'Save as copy'` -> `btn:[save as copy]`

2023-04-11 13:55 UTC, tjerman requested changes

2023-04-11 13:55 UTC, tjerman commented on src/modules/integrator-guide/pages/compose-configuration/index.adoc
> +  "annotations": [{
I'd consider also cutting most of the photo (the top part which is just a mess of page blocks) as well as potentially using `focus`.

So, I'd use `view` to cut out most of the top part, and then `focus` to blur everything outside of the toolbar.

2023-04-11 13:55 UTC, tjerman commented on src/modules/integrator-guide/pages/compose-configuration/index.adoc
> +    "rel": "compose-configuration/copied-page.png",
Please have all images captured at 1920 x 1080. Use `view` to cut out what you need. This makes it easier to update screenshots later down the line.

2023-04-11 13:55 UTC, tjerman commented on src/modules/integrator-guide/pages/compose-configuration/index.adoc
> +=== Copying list pages
I'd consider moving this under the `== Page builder` section just because it doesn't really fit in here -- seems a bit forced to me.

2023-04-12 13:54 UTC, tjerman commented on src/modules/integrator-guide/pages/compose-configuration/index.adoc
> +
I'd move this block to line 654 primarily because it can get overlooked right after images

2023-04-12 14:10 UTC, merged