Add geometry page block documentation
cortezaproject/corteza-docs pull request #390
Opened 2023-04-20 12:52 UTC by kelanik8

Geometry page block documentation

2023-04-21 06:57 UTC, tjerman requested changes

2023-04-21 06:57 UTC, tjerman commented on src/modules/integrator-guide/pages/compose-configuration/page-blocks.adoc
> +
just one empty line please

2023-04-21 06:57 UTC, tjerman commented on src/modules/integrator-guide/pages/compose-configuration/page-blocks.adoc
> +|===
empty line at the end please

2023-04-21 06:57 UTC, tjerman commented on src/modules/integrator-guide/pages/compose-configuration/page-blocks.adoc
> +The *geometry page block* allows you to show a map with a marker, lines and polygons from different geometry values of different record sources which are rendered on the map.
`...map with a marker, lines...` -> `...map with markers, lines...`

2023-04-21 06:57 UTC, tjerman commented on src/modules/integrator-guide/pages/compose-configuration/page-blocks.adoc
> +The *geometry page block* allows you to show a map with a marker, lines and polygons from different geometry values of different record sources which are rendered on the map.
`...record sources which are rendered on the map.` -> `...record sources.`

The being rendered on the map is already explained in the first bit -- `...allows you to show a map with...`

2023-04-21 06:57 UTC, tjerman commented on src/modules/integrator-guide/pages/compose-configuration/page-blocks.adoc
> +Geometry page block can render a map within certain map constraints.
I don't understand this part.

2023-04-24 12:42 UTC, tjerman requested changes

2023-04-24 12:42 UTC, tjerman commented on src/modules/integrator-guide/pages/compose-configuration/page-blocks.adoc
> +Defines if the map should be locked to the bounds of the marker.
Should this be explained a bit more? I'm not sure what exactly this is about.
In the bounds of the displayed pins?

2023-04-24 12:42 UTC, tjerman commented on src/modules/integrator-guide/pages/compose-configuration/page-blocks.adoc
> +image:compose-configuration/page-block-reference/added-geometry.png[...,49%,role="preview data-zoomable"]
Replace with screenshots that follow the guidelines

2023-04-25 08:32 UTC, tjerman requested changes
Your screenshots still don't follow [the guidelines](https://docs.cortezaproject.org/corteza-docs/2023.3/developer-guide/documentation/annotations.html)

2023-04-25 08:32 UTC, tjerman commented on src/modules/integrator-guide/pages/compose-configuration/page-blocks.adoc
> +Defines if the map should be prevented from being panned out or zoomed out of the current rectangular area of the map.
What are the bounds defined by?

2023-04-26 21:09 UTC, kelanik8 commented on src/modules/integrator-guide/pages/compose-configuration/page-blocks.adoc
> +Defines if the map should be prevented from being panned out or zoomed out of the current rectangular area of the map.
lat and lng

2023-05-11 07:15 UTC, tjerman approved these changes
lgtm; good job

2023-05-30 17:00 UTC, merged